### ISSUE TITLE
Apply Method to New Dataset / How to Extract the Mesh

### ISSUE THREAD

**Issue by deeplearningfam** [henzler/platonicgan#2]
Hi @henzler , thanks a lot for the great work!

I want to apply your method to my own car dataset. Could you give me some advice if I would need to change something? These would be RGBA images of cars. For now I tried to use the default config with adjusted paths. Currently, you sample uniformly on the full sphere - is this correct? Here I would adjust the sample range - but is there something else I need to take into account?

Also, could you provide some hints on how to extract the mesh? I tried to take the output volume, select a threshold of 0.5, and apply marching cubes to this - however, my results for the tree dataset look different from your your result in the paper. 

Thanks so much in advance!

**Comment by henzler** [comment]
Yes, currently the method samples uniformly on the full sphere and you would need to adjust the code for a different sampling.

The results in the paper are volume renderings and no mesh was created there. I never tried creating a mesh from my results with marching cubes so I cannot give you advice on this.

**Comment by deeplearningfam** [comment]
Hi @henzler , thanks so much for your fast answer! I have two follow-up questions:

1. But your data are simple collections of RGBA images - is that correct?
2. If you never extracted a mesh, you could you explain how you were able to evaluate the Chamfer distance or IoU, e.g. in [table 2 of the main paper](https://arxiv.org/pdf/1811.11606.pdf)?

Thanks for your amazing help!

**Comment by henzler** [comment]
1. Yes
2. You can see the volume as a point cloud and hence calculate those metrics.
